# Generated by Django 3.1.1 on 2020-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0013_actionlog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="created_network_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
