# Generated by Django 3.1.1 on 2020-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0014_allow_blank_network_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="regionsettings", name="gvl_image_id",),
    ]
