# Generated by Django 3.1.1 on 2020-10-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0023_auto_20201021_1111"),
        ("openstack", "0015_drop_region_gvl_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionsettings",
            name="horizon_endpoint",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="userdb.team",
            ),
        ),
    ]
