# Generated by Django 3.1.1 on 2021-03-25 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openstack", "0015_auto_20210324_1006"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerLeaseRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed", models.BooleanField(default=False)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response", models.TextField()),
                ("granted", models.BooleanField(default=False)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_request_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "server_lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openstack.serverlease",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
