# Generated by Django 3.1.1 on 2021-03-25 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openstack", "0016_serverleaserequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverleaserequest",
            name="actioned_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_request_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
