# Generated by Django 3.1.1 on 2021-03-25 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openstack", "0017_auto_20210325_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverleaserequest",
            name="granted",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="serverleaserequest",
            name="responded_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="serverleaserequest",
            name="server_lease",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="openstack.serverlease",
            ),
        ),
        migrations.AlterField(
            model_name="serverleaserequest",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lease_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
