# Generated by Django 3.1.1 on 2021-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0018_keypair"),
    ]

    operations = [
        migrations.AddField(
            model_name="regionsettings",
            name="max_volume_size_gb",
            field=models.IntegerField(
                default=5000, verbose_name="Maximum allowed volume size in GB"
            ),
        ),
    ]
