# Generated by Django 3.1.1 on 2021-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0018_auto_20210325_1542"),
    ]

    operations = [
        migrations.DeleteModel(name="ActionLog",),
    ]
