# Generated by Django 3.1.1 on 2021-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0019_delete_actionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverlease",
            name="last_renewed_at",
            field=models.DateTimeField(editable=False),
        ),
    ]
