# Generated by Django 3.1.1 on 2021-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0020_serverlease"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverlease",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="serverlease",
            name="shelved",
            field=models.BooleanField(default=False),
        ),
    ]
