# Generated by Django 3.1.1 on 2021-03-10 18:23

from django.conf import settings
from django.db import migrations, models
import openstack.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openstack", "0021_auto_20210310_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keypair",
            name="public_key",
            field=models.TextField(
                validators=[openstack.validators.validate_public_key],
                verbose_name="SSH public key",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="keypair", unique_together={("user", "public_key")},
        ),
    ]
