# Generated by Django 3.1.1 on 2021-05-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0024_auto_20210406_1525"),
        ("openstack", "0021_auto_20210507_0938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="created_tenant_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_tenant_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="tenant",
            unique_together={("team", "region")},
        ),
    ]
