# Generated by Django 3.1.1 on 2021-03-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0022_auto_20210310_1823"),
    ]

    operations = [
        migrations.AddField(
            model_name="serverlease",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
