# Generated by Django 3.1.1 on 2021-03-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0023_serverlease_last_reminder_sent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hypervisorstats", options={"verbose_name_plural": "Hypervisor Stats"},
        ),
        migrations.AlterModelOptions(
            name="regionsettings", options={"verbose_name_plural": "Region Settings"},
        ),
    ]
