/* -- ROOT STORE -- */

export const INIT_STORE = "INIT_STORE";
export const SET_ACTIVE_TEAM = "SET_ACTIVE_TEAM";
export const SET_FILTER_TENANT = "SET_FILTER_TENANT";
export const FETCH_ALL_TENANT_DATA = "FETCH_ALL_TENANT_DATA";
export const FETCH_HYPERVISOR_STATS = "FETCH_HYPERVISOR_STATS";
export const FETCH_TEAM_SPECIFIC_DATA = "FETCH_TEAM_SPECIFIC_DATA";
export const FETCH_TENANT_SPECIFIC_DATA = "FETCH_TENANT_SPECIFIC_DATA";
export const FETCH_TENANT_VOLUME_TYPES = "FETCH_TENANT_VOLUME_TYPES";
export const FETCH_USER = "FETCH_USER";
export const UPDATE_TEAM = "UPDATE_TEAM";
export const UPDATE_USER = "UPDATE_USER";

/* -- MODULES (not namespaced) -- */

// Key pairs
export const CREATE_KEY_PAIR = "CREATE_KEY_PAIR";
export const DELETE_KEY_PAIR = "DELETE_KEY_PAIR";
export const FETCH_KEY_PAIRS = "FETCH_KEY_PAIRS";
export const SET_DEFAULT_KEY_PAIR = "SET_DEFAULT_KEY_PAIR";

// Flavors
export const FETCH_TENANT_FLAVORS = "FETCH_TENANT_FLAVORS";

// Images
export const FETCH_TENANT_IMAGES = "FETCH_TENANT_IMAGES";

// Instances
export const CREATE_INSTANCE = "CREATE_INSTANCE";
export const DELETE_INSTANCE = "DELETE_INSTANCE";
export const FETCH_INSTANCE = "FETCH_INSTANCE";
export const FETCH_TENANT_INSTANCES = "FETCH_INSTANCES_FOR_TENANT";
export const REMOVE_INSTANCE_BY_ID = "REMOVE_INSTANCE_BY_ID";
export const TRANSITION_INSTANCE = "TRANSITION_INSTANCE";

// Invitations
export const CREATE_INVITATION = "CREATE_INVITATION";
export const DELETE_INVITATION = "DELETE_INVITATION";
export const FETCH_INVITATIONS = "FETCH_INVITATIONS";

// Team Members
export const DELETE_TEAM_MEMBER = "DELETE_TEAM_MEMBER";
export const FETCH_TEAM_MEMBERS = "FETCH_TEAM_MEMBERS";

// Volumes
export const ATTACH_VOLUME = "ATTACH_VOLUME";
export const CREATE_VOLUME = "CREATE_VOLUME";
export const DELETE_VOLUME = "DELETE_VOLUME";
export const DETACH_VOLUME = "DETACH_VOLUME";
export const FETCH_TENANT_VOLUMES = "FETCH_TENANT_VOLUMES";
export const FETCH_VOLUME = "FETCH_VOLUME";

// Polling
export const CREATE_POLLING_TARGET = "CREATE_POLLING_TARGET";
export const FETCH_POLLING_TARGETS = "FETCH_POLLING_TARGETS";
