/* -- ROOT STORE -- */
export const DEFAULT_TEAM_ID = "DEFAULT_TEAM_ID";
export const DEFAULT_TENANT = "DEFAULT_TENANT";
export const FILTER_TENANT = "FILTER_TENANT";
export const GET_REGION_BY_ID = "GET_REGION_BY_ID";
export const GET_REGION_FOR_TENANT = "GET_REGION_FOR_TENANT";
export const GET_REGION_NAME_FOR_TENANT = "GET_REGION_NAME_FOR_TENANT";
export const GET_TEAM_BY_ID = "GET_TEAM_BY_ID";
export const GET_TENANT_BY_ID = "GET_TENANT_BY_ID";
export const LOADING = "LOADING";
export const TEAM = "TEAM";
export const TENANTS = "TENANTS";
export const USER_IS_ADMIN = "USER_IS_ADMIN";
export const USER_FULL_NAME = "USER_FULL_NAME";
export const FAQS_KEYPAIRS = "FAQS_KEYPAIRS";
export const FAQS_SERVERS = "FAQS_SERVERS";
export const FAQS_VOLUMES = "FAQS_VOLUMES";

/* -- MODULES (not namespaced) -- */

// Announcements
export const NEWS_ANNOUNCEMENTS = "NEWS_ANNOUNCEMENTS";
export const SERVICE_ANNOUNCEMENTS = "SERVICE_ANNOUNCEMENTS";

// Flavors
export const GET_FLAVOR_BY_ID = "GET_FLAVOR_BY_ID";
export const GET_FLAVORS_FOR_TENANT = "GET_FLAVORS_FOR_TENANT";

// Images
export const GET_IMAGE_BY_ID = "GET_IMAGE_BY_ID";
export const GET_IMAGES_FOR_TENANT = "GET_IMAGES_FOR_TENANT";

// Instances
export const ALL_INSTANCES = "ALL_INSTANCES";
export const GET_INSTANCE_BY_ID = "GET_INSTANCE_BY_ID";
export const GET_INSTANCES_FOR_TENANT = "GET_INSTANCES_FOR_TENANT";
export const GET_INSTANCE_IS_POLLING = "GET_INSTANCE_IS_POLLING";
export const INSTANCES_FOR_FILTER_TENANT = "INSTANCES_FOR_FILTER_TENANT";
export const LIVE_INSTANCES = "LIVE_INSTANCES";
export const LIVE_INSTANCES_FOR_FILTER_TENANT =
  "LIVE_INSTANCES_FOR_FILTER_TENANT";
export const TOTAL_TEAM_INSTANCES = "TOTAL_TEAM_INSTANCES";
export const TOTAL_TEAM_VCPUS = "TOTAL_TEAM_VCPUS";
export const TOTAL_TEAM_RAM_GB = "TOTAL_TEAM_RAM_GB";

// Invitations
export const ALL_INVITATIONS = "ALL_INVITATIONS";

// Key Pairs
export const GET_KEY_PAIR_BY_ID = "GET_KEY_PAIR_BY_ID";
export const GET_KEY_PAIR_IS_DEFAULT = "GET_KEY_PAIR_IS_DEFAULT";
export const DEFAULT_KEY_PAIR = "DEFAULT_KEY_PAIR";

// Team members
export const ADMIN_TEAM_MEMBERS = "ADMIN_TEAM_MEMBERS";
export const ALL_TEAM_MEMBERS = "ALL_TEAM_MEMBERS";
export const GET_TEAM_MEMBER_BY_ID = "GET_TEAM_MEMBER_BY_ID";

// Volumes
export const ALL_VOLUMES = "ALL_VOLUMES";
export const GET_MAX_VOLUME_SIZE_FOR_TENANT = "GET_MAX_VOLUME_SIZE_FOR_TENANT";
export const GET_VOLUME_BY_ID = "GET_VOLUME_BY_ID";
export const GET_VOLUME_IS_POLLING = "GET_VOLUME_IS_POLLING";
export const GET_VOLUMES_FOR_TENANT = "GET_VOLUMES_FOR_TENANT";
export const TOTAL_TEAM_CAPACITY_GB = "TOTAL_TEAM_CAPACITY_GB";
export const TOTAL_TEAM_VOLUMES = "TOTAL_TEAM_VOLUMES";
export const VOLUMES_FOR_FILTER_TENANT = "VOLUMES_FOR_FILTER_TENANT";

// Volume Types
export const GET_VOLUME_TYPES_FOR_TENANT = "GET_VOLUME_TYPES_FOR_TENANT";

// Polling
export const GET_ITEM_IS_POLLING = "GET_ITEM_IS_POLLING";
