/* -- ROOT STORE -- */

export const INIT_LICENCE_TERMS = "INIT_LICENCE_TERMS";
export const MODIFY_TEAM = "MODIFY_TEAM";
export const SET_ACTIVE_TEAM_ID = "SET_ACTIVE_TEAM_ID";
export const SET_FAQS = "SET_FAQS";
export const SET_FILTER_TENANT_ID = "SET_FILTER_TENANT_ID";
export const SET_HYPERVISOR_STATS = "SET_HYPERVISOR_STATS";
export const SET_READY = "SET_READY";
export const SET_REGIONS = "SET_REGIONS";
export const SET_TEAMS = "SET_TEAMS";
export const SET_TEAM_INITIALIZED = "SET_TEAM_INITIALIZED";
export const SET_USER = "UPDATE_USER";

/* -- MODULES (not namespaced) -- */

// Announcements
export const SET_ANNOUNCEMENTS = "SET_ANNOUNCEMENTS";

// Flavors
export const SET_FLAVORS = "SET_FLAVORS";

// Images
export const SET_IMAGES = "SET_IMAGES";

// Instances
export const ADD_INSTANCE = "ADD_INSTANCE";
export const MODIFY_INSTANCE = "MODIFY_INSTANCE";
export const SET_INSTANCES = "SET_INSTANCE";
export const SET_INSTANCES_LOADING = "SET_INSTANCES_LOADING";

// Invitations
export const ADD_INVITATION = "ADD_INVITATION";
export const REMOVE_INVITATION_BY_ID = "REMOVE_INVITATION_BY_ID";
export const SET_INVITATIONS = "SET_INVITATIONS";

// KeyPairs
export const ADD_KEY_PAIR = "ADD_KEY_PAIR";
export const SET_KEY_PAIRS = "SET_KEY_PAIRS";
export const REMOVE_KEY_PAIR_BY_ID = "REMOVE_KEY_PAIR_BY_ID";

// Polling
export const UPDATE_OR_CREATE_POLLING_TARGET = "ADD_POLLING_TARGET";
export const REMOVE_POLLING_TARGET = "REMOVE_POLLING_TARGET";
export const CLEAR_POLLING_SYMBOL = "CLEAR_POLLING_SYMBOL";
export const SET_POLLING_SYMBOL = "SET_POLLING_SYMBOL";

// Team Members
export const REMOVE_TEAM_MEMBER_BY_ID = "REMOVE_TEAM_MEMBER_BY_ID";
export const SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS";

// Volume Types
export const SET_VOLUME_TYPES = "SET_VOLUME_TYPES";

// Volumes
export const ADD_VOLUME = "ADD_VOLUME";
export const MODIFY_VOLUME = "MODIFY_VOLUME";
export const REMOVE_VOLUME_BY_ID = "REMOVE_VOLUME_BY_ID";
export const SET_VOLUMES = "SET_VOLUMES";
export const SET_VOLUMES_LOADING = "SET_VOLUMES_LOADING";
