# Generated by Django 3.1.1 on 2021-03-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import userdb.models


def forward_port_user_profile(apps, schema_editor):
    Profile = apps.get_model("userdb", "Profile")
    User = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias
    for user in User.objects.using(db_alias).all():
        Profile.objects.using(db_alias).create(user=user, email_validated=True)


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0014_auto_20210323_1349"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("userdb", "0020_region_disable_new_instances"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceAcceptance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LicenceVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=15, unique=True)),
                ("licence_terms", tinymce.models.HTMLField()),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("validity_period_days", models.IntegerField(default="90")),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        related_query_name="profile",
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                ("email_validated", models.BooleanField(default=False)),
                (
                    "new_email_pending_verification",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="licence_expiry",
            field=models.DateTimeField(default=userdb.models.licence_expiry_default),
        ),
        migrations.AddField(
            model_name="team",
            name="licence_last_reminder_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(
                related_name="teams",
                through="userdb.TeamMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="to_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="userdb.team",
                verbose_name="Team to invite user to",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="default_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userdb.region",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="department",
            field=models.CharField(max_length=50, verbose_name="Department"),
        ),
        migrations.AlterField(
            model_name="team",
            name="institution",
            field=models.CharField(max_length=100, verbose_name="Institution"),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Group or team name"),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_teammember"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="default_keypair",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="openstack.keypair",
            ),
        ),
        migrations.AddField(
            model_name="licenceacceptance",
            name="licence_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="userdb.licenceversion"
            ),
        ),
        migrations.AddField(
            model_name="licenceacceptance",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licence_acceptances",
                to="userdb.team",
            ),
        ),
        migrations.AddField(
            model_name="licenceacceptance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="licence_acceptances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forward_port_user_profile),
    ]
