# Generated by Django 3.1.1 on 2021-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0014_auto_20210323_1349"),
        ("home", "0002_auto_20210224_1255"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("userdb", "0021_auto_20210323_1349"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
