# Generated by Django 3.1.1 on 2020-10-21 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0022_auto_20201008_1009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="to_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="userdb.team",
                verbose_name="Team to invite user to",
            ),
        ),
    ]
