# Generated by Django 3.1.1 on 2021-01-04 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0023_auto_20201021_1111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="default_region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="userdb.region",
            ),
        ),
    ]
