# Generated by Django 3.1.1 on 2021-01-14 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("openstack", "0018_keypair"),
        ("userdb", "0024_auto_20210104_1500"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        related_query_name="profile",
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "validation_link",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("email_validated", models.BooleanField(default=False)),
                (
                    "default_keypair",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="openstack.keypair",
                    ),
                ),
            ],
        ),
    ]
