# Generated by Django 3.1.1 on 2021-01-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0026_auto_20210120_1723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Group or team name"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("team", "user"), name="unique_teammember"
            ),
        ),
    ]
