# Generated by Django 3.1.1 on 2021-01-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0027_auto_20210121_1950"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="validation_link",),
    ]
