# Generated by Django 3.1.1 on 2021-02-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0028_remove_profile_validation_link"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="invitation", name="unique_invitation",),
    ]
