# Generated by Django 3.1.1 on 2021-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0029_auto_20210209_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="new_email_pending_verification",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
