# Generated by Django 3.1.1 on 2021-03-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("userdb", "0030_profile_new_email_pending_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenceVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=15, unique=True)),
                ("licence_terms", tinymce.models.HTMLField()),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("validity_period_days", models.IntegerField(default="90")),
            ],
        ),
        migrations.CreateModel(
            name="LicenceAcceptance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "licence_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="userdb.licenceversion",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licence_acceptances",
                        to="userdb.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licence_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
