# Generated by Django 3.1.1 on 2021-03-05 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import userdb.models


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0031_licenceacceptance_licenceversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenceacceptance",
            name="version",
            field=models.ForeignKey(
                default=userdb.models.LicenceVersionManager.current,
                on_delete=django.db.models.deletion.PROTECT,
                to="userdb.licenceversion",
            ),
        ),
        migrations.AlterField(
            model_name="licenceversion",
            name="effective_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
