# Generated by Django 3.1.1 on 2021-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userdb", "0032_auto_20210322_1327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Group or team name"),
        ),
    ]
